*** Settings ***
Resource    ../objects/App.resource
# add additional Resource lines for each object referenced in the test fragments


Documentation    Import file for functional tests 
...
...    This file maps high level /When/Then keywords to object resources.  
...
...    The object resource files contain the implementation details for the
...    different test methods of each object.
...

*** Keywords ***
# drop test fragments for each given/ when/ then/ keyword here
